name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - tsm-jekyll-upgrade

jobs:
  github-pages:
    runs-on: ubuntu-latest
    env:
      remote_branch: tsm-jekyll-upgrade-out
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true
      - name: Install dependencies
        run: |
          sudo apt-get install jq
          npm install
      - name: Set up build directory
        shell: bash
        run: |
          mkdir ../jekyll_build
          cd ../jekyll_build
          git clone https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git .
          git switch -c $remote_branch
          git branch --set-upstream-to=origin/$remote_branch $remote_branch
          git pull
      - name: Jekyll build
        run: |
          export BASE_URL=$(curl -H "Accept: application/vnd.github.v3+json" https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/$GITHUB_REPOSITORY/pages | jq -r .html_url | sed 's|https\?\:\/\/[^\/]*\(\.*\)|\1|')
          echo "Base URL: $BASE_URL"
          curl -H "Accept: application/vnd.github.v3+json" https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/$GITHUB_REPOSITORY/pages
          bundle exec jekyll build -b $BASE_URL -s $GITHUB_WORKSPACE -d $GITHUB_WORKSPACE/../jekyll_build
      - name: Create legacy JSON files
        working-directory: ../jekyll_build
        shell: bash
        run: for f in nb/{eyes,fish_0,fish_1,fish_off,gaboemote,gaussian,gordonramsay,LMS,test,typo_0}; do cp $f.js $f.json; done
      - name: Minify JS
        run: npm run minify
        env:
          MIN_JS_DIR: ../jekyll_build/nb/
      - name: Jekyll deploy
        working-directory: ../jekyll_build
        run: |
          touch .nojekyll
          git config user.name "$GITHUB_ACTOR" && \
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" && \
          git add . && \
          git commit --allow-empty -m "jekyll build from Action $GITHUB_SHA" && \
          git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git $remote_branch:$remote_branch
